### ISSUE TITLE
AssertionError: Note

### ISSUE THREAD

**Issue by pschmitt** [archibate/nvim-gpt#3]
The assert here fires on a new install when invoking `:GPTOpen`:

https://github.com/archibate/nvim-gpt/blob/7738d94f010e50d4229fc16bc24bf13cd4c5a2f8/rplugin/python3/py_nvim_gpt/plugin.py#L80

Relevant template:

https://github.com/archibate/nvim-gpt/blob/7738d94f010e50d4229fc16bc24bf13cd4c5a2f8/rplugin/python3/py_nvim_gpt/keymaps.py#L34

Full trace:

```
Error detected while processing function remote#define#CommandBootstrap[5]..remote#define#request:                                                             
line    2:                                                                                                                                                     
error caught in request handler '/home/pschmitt/.local/share/lunarvim/site/pack/lazy/opt/nvim-gpt/rplugin/python3/py_nvim_gpt:command:GPTOpen []'              
Traceback (most recent call last):                                                                                                                             
  File "/usr/lib/python3.10/site-packages/pynvim/plugin/host.py", line 124, in _on_request                                                                     
    rv = handler(*args)                                                                                                                                        
  File "/usr/lib/python3.10/site-packages/pynvim/plugin/host.py", line 86, in _wrap_delayed_function                                                           
    plugin = cls(self._configure_nvim_for(cls))                                                                                                                
  File "/home/pschmitt/.local/share/lunarvim/site/pack/lazy/opt/nvim-gpt/rplugin/python3/py_nvim_gpt/plugin.py", line 80, in __init__                          
    assert args[0] == 'GPTTemplate', args[0]                                                                                                                   
AssertionError: Note                                                                                                                                           
Error invoking '/home/pschmitt/.local/share/lunarvim/site/pack/lazy/opt/nvim-gpt/rplugin/python3/py_nvim_gpt:command:GPTOpen' on channel 4 (python3-rplugin-hos
t):                                                                                                                                                            
AssertionError('Note')                                                                                                                                         
Traceback (most recent call last):                                                                                                                             
  File "/usr/lib/python3.10/site-packages/pynvim/msgpack_rpc/session.py", line 195, in handler                                                                 
    rv = self._request_cb(name, args)                                                                                                                          
  File "/usr/lib/python3.10/site-packages/pynvim/api/nvim.py", line 210, in filter_request_cb                                                                  
    result = request_cb(name, args)                                                                                                                            
  File "/usr/lib/python3.10/site-packages/pynvim/plugin/host.py", line 124, in _on_request                                                                     
    rv = handler(*args)                                                                                                                                        
  File "/usr/lib/python3.10/site-packages/pynvim/plugin/host.py", line 86, in _wrap_delayed_function                                                           
    plugin = cls(self._configure_nvim_for(cls))                                                                                                                
  File "/home/pschmitt/.local/share/lunarvim/site/pack/lazy/opt/nvim-gpt/rplugin/python3/py_nvim_gpt/plugin.py", line 80, in __init__                          
    assert args[0] == 'GPTTemplate', args[0]                                                                                                                   
AssertionError: Note                                                                                                                                           
```

Lazy config:

```lua
local has_openai = os.getenv("OPENAI_API_KEY") ~= nil

[...]
  {
    'archibate/nvim-gpt',
    -- optional for supporting ':Telescope nvim-gpt gpt_model/gpt_history/gpt_template' commands
    dependencies = { 'nvim-telescope/telescope.nvim' },
    config = function()
      require 'nvim-gpt'.setup {
        model = 'gpt-3.5-turbo',
        window_width = 45,
        -- see more setup options in section 'Setup options' below
      }
    end,
    enabled = has_openai
  },

```

**Comment by archibate** [comment]
Thank you for reporting :+1:! Fixed in a551e1e.
