### ISSUE TITLE
module 'EdgeGPT' has no attribute 'Chatbot'

### ISSUE THREAD

**Issue by KoushikSahu** [archibate/nvim-gpt#5]
Getting the following error while trying to use bing balanced model:

```
====== Mon Jul 17 02:15:20 2023 =====
GPT plugin started
setup options: {'model': 'balanced', 'window_width': 45}
BingAI started
Exception in thread Thread-1 (_worker):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/koushiksahu/.local/share/nvim/lazy/nvim-gpt/rplugin/python3/py_nvim_gpt/worker_bing.py", line 31, in _worker
    bot = EdgeGPT.Chatbot(cookies=cookies)
          ^^^^^^^^^^^^^^^
AttributeError: module 'EdgeGPT' has no attribute 'Chatbot'
```

It seems like the package has updated. Either please give the version of the EdgeGPT package used for the creation of this plugin else update the plugin with the fix.

**Comment by archibate** [comment]
Thank for your contribution!
